-- 建立資料表
CREATE TABLE CONFIGURATION_VALUES
(
  PACKAGE_NAME VARCHAR2(30) not null,
  PROPERTY     VARCHAR2(50) not null,
  VALUE        VARCHAR2(4000)
)
;

-- 建立測試資料
INSERT INTO CONFIGURATION_VALUES (PACKAGE_NAME, PROPERTY, VALUE)
VALUES ('pkgDIPayment_v03', 'CommFeeRate_NonEC', '0.001425');
INSERT INTO CONFIGURATION_VALUES (PACKAGE_NAME, PROPERTY, VALUE)
VALUES ('pkgDIPayment_v03', 'CommFeeRate_EC', '0.001325');
COMMIT;

-- 把資料讀出來檢查一下
SELECT * FROM CONFIGURATION_VALUES;